using Godot;
using System.Collections.Generic;

namespace TheFirstDay.Gameplay;

/// <summary>
/// Builds the level shell's collision at runtime.
///
/// 53 mesh instances would need 53 <c>_subresources</c> entries in the .import file to
/// generate bodies at import time. One <see cref="MeshInstance3D.CreateTrimeshCollision"/>
/// call each is less to get wrong, and keeps the .import files readable.
///
/// Runtime only, and deliberately NOT [Tool]: generating collision in the editor would add
/// 53 StaticBody3D children to the scene every time it loads, and they would be saved with
/// it.
///
/// This script used to assign the shell's materials as well, and that was a mistake worth
/// recording because it shipped a visible bug.
///
/// Unity assigned the shell's materials per renderer-SLOT, and the same FBX material name
/// resolves differently in different places: lambert1 is mat_generalTransparencia on
/// nivel's pPlane meshes but mat_general on its polySurface slot 1, and nivel_p2 reverses
/// the polySurface mapping. This file's documentation concluded that Godot "cannot express"
/// that, and applied all 73 assignments in _Ready with [Tool] so the editor matched.
///
/// The true statement is narrower. The IMPORTER cannot express it, because it keys external
/// materials by material NAME and there are only two names for four different (mesh-set,
/// slot) outcomes. The SCENE can express it exactly: <c>surface_material_override/N</c> is
/// per mesh and per slot, which is Unity's own granularity, and overriding a property on a
/// child of an instanced scene is ordinary .tscn syntax. No code was ever needed.
///
/// Because the materials came from a [Tool] C# script, the level's appearance depended on a
/// compiled C# assembly existing. On a fresh clone, where .godot/ and bin/ are both
/// gitignored, the first editor session has no assembly, so nothing applied the materials
/// and every mesh fell back to the FBX's own lambert1/lambert2 - both of which have
/// vertex_color_use_as_albedo = true. The level's vertex colours are pure red, mean
/// (0.457, 0.000, 0.000), because that red channel is DATA for level_fade.gdshader's wobble
/// and alpha rather than paint. So the whole level rendered red in the editor until it was
/// restarted. The materials now live in level.tscn, generated by
/// tools/generate_shell_overrides.gd, and that failure mode is gone.
/// </summary>
public partial class LevelShell : Node3D
{
    [Export]
    public bool GenerateCollision { get; set; } = true;

    public override void _Ready()
    {
        if (!GenerateCollision)
        {
            return;
        }

        int collided = 0;
        foreach (MeshInstance3D mesh in FindMeshes(this))
        {
            mesh.CreateTrimeshCollision();
            collided++;
        }

        GD.Print($"{Name}: built collision for {collided} meshes.");
    }

    private static List<MeshInstance3D> FindMeshes(Node node)
    {
        var found = new List<MeshInstance3D>();
        if (node is MeshInstance3D mesh)
        {
            found.Add(mesh);
        }

        foreach (Node child in node.GetChildren())
        {
            found.AddRange(FindMeshes(child));
        }

        return found;
    }
}
