using Godot;
using System.Collections.Generic;

namespace TheFirstDay.Gameplay;

/// <summary>
/// Builds the level shell's collision at runtime.
///
/// 53 mesh instances would need 53 <c>_subresources</c> entries in the .import file to
/// generate bodies at import time. One <see cref="MeshInstance3D.CreateTrimeshCollision"/>
/// call each is less to get wrong, and keeps the .import files readable.
///
/// Runtime only, and deliberately NOT [Tool]: generating collision in the editor would add
/// 53 StaticBody3D children to the scene every time it loads, and they would be saved with
/// it.
///
/// This script used to assign the shell's materials as well, and that was a mistake worth
/// recording because it shipped a visible bug.
///
/// Unity assigned the shell's materials per renderer-SLOT, and the same FBX material name
/// resolves differently in different places: lambert1 is mat_generalTransparencia on
/// nivel's pPlane meshes but mat_general on its polySurface slot 1, and nivel_p2 reverses
/// the polySurface mapping. This file's documentation concluded that Godot "cannot express"
/// that, and applied all 73 assignments in _Ready with [Tool] so the editor matched.
///
/// The true statement is narrower. The IMPORTER cannot express it, because it keys external
/// materials by material NAME and there are only two names for four different (mesh-set,
/// slot) outcomes. The SCENE can express it exactly: <c>surface_material_override/N</c> is
/// per mesh and per slot, which is Unity's own granularity, and overriding a property on a
/// child of an instanced scene is ordinary .tscn syntax. No code was ever needed.
///
/// Because the materials came from a [Tool] C# script, the level's appearance depended on a
/// compiled C# assembly existing. On a fresh clone, where .godot/ and bin/ are both
/// gitignored, the first editor session has no assembly, so nothing applied the materials
/// and every mesh fell back to the FBX's own lambert1/lambert2 - both of which have
/// vertex_color_use_as_albedo = true. The level's vertex colours are pure red, mean
/// (0.457, 0.000, 0.000), because that red channel is DATA for level_fade.gdshader's wobble
/// and alpha rather than paint. So the whole level rendered red in the editor until it was
/// restarted. The materials now live in level.tscn, generated by
/// tools/generate_shell_overrides.gd, and that failure mode is gone.
/// </summary>
public partial class LevelShell : Node3D
{
    [Export]
    public bool GenerateCollision { get; set; } = true;

    /// <summary>
    /// Names of this shell's meshes whose collision the player may STEP UP onto - see
    /// PlayerCharacter.ClimbableGroup, which is opt-in: nothing is climbable unless marked.
    ///
    /// The tag has to be applied from here rather than written into level.tscn, because the bodies
    /// it belongs on do not exist in the scene file. CreateTrimeshCollision builds them at load,
    /// named "&lt;mesh&gt;_col". And the mesh nodes themselves are no better a home: they live inside
    /// the region tools/generate_shell_overrides.gd owns, so a group added there is wiped the next
    /// time that tool runs. This list sits on the Shell node, outside that region, and the shell
    /// that builds the collision is the honest owner of which parts of it are climbable.
    ///
    /// Both stair meshes are needed for the staircase before the end line, not just the obvious
    /// one: the risers are on polySurface18, but the FINAL step lands on polySurface32, so tagging
    /// only the first leaves the character stuck on the last one. Measured from the floor profile,
    /// which goes 11.78 -&gt; 12.00 across that boundary.
    /// </summary>
    [Export]
    public string[] ClimbableMeshes { get; set; } = System.Array.Empty<string>();

    public override void _Ready()
    {
        if (!GenerateCollision)
        {
            return;
        }

        int collided = 0;
        int climbable = 0;
        var wanted = new HashSet<string>(ClimbableMeshes);
        foreach (MeshInstance3D mesh in FindMeshes(this))
        {
            mesh.CreateTrimeshCollision();
            collided++;

            if (!wanted.Contains(mesh.Name))
            {
                continue;
            }

            // CreateTrimeshCollision adds the body as a child of the mesh. Tag the body itself
            // rather than the mesh, so the step-up can test what it actually collided with.
            foreach (Node child in mesh.GetChildren())
            {
                if (child is StaticBody3D body)
                {
                    body.AddToGroup(PlayerCharacter.DefaultClimbableGroup);
                    climbable++;
                }
            }
        }

        // Named rather than counted, because a typo in ClimbableMeshes is silent otherwise: the
        // mesh simply never matches and the character sticks with nothing to explain why.
        var missing = new List<string>();
        foreach (string name in wanted)
        {
            if (GetNodeOrNull(name) is null && FindMeshes(this).Find(m => m.Name == name) is null)
            {
                missing.Add(name);
            }
        }

        GD.Print($"{Name}: built collision for {collided} meshes, {climbable} climbable.");
        if (missing.Count > 0)
        {
            GD.PushWarning($"{Name}: ClimbableMeshes names no mesh called {string.Join(", ", missing)}; nothing was tagged for it.");
        }
    }

    private static List<MeshInstance3D> FindMeshes(Node node)
    {
        var found = new List<MeshInstance3D>();
        if (node is MeshInstance3D mesh)
        {
            found.Add(mesh);
        }

        foreach (Node child in node.GetChildren())
        {
            found.AddRange(FindMeshes(child));
        }

        return found;
    }
}
